'use client'

import Image from 'next/image'
import { useState } from 'react'
import { ArrowRight, Check, Globe2, Hammer, MapPin, Menu, Phone, ShoppingCart, Truck, Wrench, X } from 'lucide-react'
import { CartButton } from '@/components/cart-drawer'
import { HeroSlider } from '@/components/hero-slider'

const whatsapp = 'https://wa.me/254721270670?text=Hi%2C%20I%27m%20interested%20in%20your%20steel%20and%20hardware%20products.'
const products = [
  { title: 'Structural Steel & Fabrication', icon: Hammer, image: '/Structural Steel.png', text: 'Reinforcement bars, hollow sections, welding supplies, and fabrication essentials for strong, lasting builds.', items: ['High-strength reinforcement steel', 'Square & rectangular hollow sections', 'Materials for gates, grills & frameworks'] },
  { title: 'Masonry & Construction', icon: Truck, image: '/hardware 7.jpg', text: 'The dependable essentials that keep your foundation, walls, and roofing work moving without delays.', items: ['Bamburi, Simba & Savannah cement', 'Binding wire and timber nails', 'Roofing nails in varied configurations'] },
  { title: 'General Hardware Supplies', icon: Wrench, image: '/Hardware 6.jpg', text: 'Practical tools, fasteners, plumbing, and electrical basics for every site, workshop, and home project.', items: ['Hand tools and fasteners', 'PVC piping and conduit pipes', 'Conduit accessories & maintenance hardware'] },
]
const reasons = ['Wide product range', 'Competitive pricing', 'Local Juja presence', 'Trusted by contractors']

export default function Home() {
  const [menuOpen, setMenuOpen] = useState(false)
  const closeMenu = () => setMenuOpen(false)
  return (
    <main className="min-h-screen overflow-hidden bg-background text-foreground">
      <header className="fixed inset-x-0 top-0 z-50 border-b border-white/10 bg-steel/95 text-steel-foreground backdrop-blur-md"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-3 lg:px-8"><a href="#home" onClick={closeMenu} className="flex items-center gap-3" aria-label="Muhoro Steel Hardware home"><img src="/msh-logo.jpg" alt="Muhoro Steel Hardware" className="h-16 w-auto object-contain" /><span className="hidden font-display text-lg font-bold tracking-tight sm:block">MUHORO <span className="text-accent">STEEL HARDWARE</span></span></a><nav className={`${menuOpen ? 'flex' : 'hidden'} absolute left-0 right-0 top-full flex-col gap-5 border-b border-white/10 bg-steel px-5 py-6 md:static md:flex md:flex-row md:items-center md:border-0 md:bg-transparent md:p-0`}>{['Home', 'About', 'Products', 'Delivery', 'Why Muhoro', 'Contact'].map((item) => <a key={item} href={`#${item.toLowerCase().replace(' ', '-')}`} onClick={closeMenu} className="text-sm font-semibold text-steel-foreground/80 transition hover:text-white">{item}</a>)}</nav><div className="flex items-center gap-2"><a href="/products" className="hidden rounded-full border border-white/20 px-4 py-2.5 text-sm font-bold text-white transition hover:border-white sm:inline-flex">Shop</a><a href={whatsapp} className="hidden rounded-full bg-whatsapp px-4 py-2.5 text-sm font-bold text-white shadow-lg shadow-whatsapp/20 transition hover:brightness-110 lg:inline-flex">WhatsApp</a><CartButton /><a href={whatsapp} className="hidden rounded-sm bg-accent px-4 py-2.5 text-sm font-bold text-white transition hover:bg-accent/90 xl:inline-flex">Request Quote</a><button aria-label={menuOpen ? 'Close menu' : 'Open menu'} aria-expanded={menuOpen} onClick={() => setMenuOpen(!menuOpen)} className="rounded-md p-2 text-steel-foreground md:hidden">{menuOpen ? <X size={22} /> : <Menu size={22} />}</button></div></div></header>
      <section id="home" className="relative flex min-h-[680px] items-center bg-steel pt-24 text-steel-foreground"><HeroSlider /><div className="relative mx-auto grid w-full max-w-7xl gap-12 px-5 py-20 lg:grid-cols-2 lg:px-8 lg:py-28"><div className="max-w-2xl"><p className="mb-6 flex items-center gap-3 text-sm font-bold uppercase tracking-[.22em] text-accent"><span className="h-px w-10 bg-accent" /> Juja · Kiambu County</p><h1 className="font-display text-5xl font-black uppercase leading-[.93] tracking-tight text-balance sm:text-7xl">Quality steel.<br /><span className="text-accent">Reliable hardware.</span><br />Built to last.</h1><p className="mt-7 max-w-xl text-lg leading-8 text-steel-foreground/80">Structural steel, cement, fabrication materials, and hardware supplies for contractors, fundis, and homeowners across Juja and Kiambu County.</p><div className="mt-9 flex flex-wrap gap-3"><a href={whatsapp} className="inline-flex items-center gap-2 rounded-full bg-whatsapp px-6 py-3.5 font-bold text-white shadow-xl shadow-whatsapp/20 transition hover:brightness-110">Chat on WhatsApp <ArrowRight size={18} /></a><a href="#products" className="inline-flex items-center rounded-sm border border-white/40 px-6 py-3.5 font-bold text-white transition hover:border-white hover:bg-white/10">View Products</a></div></div></div></section>
      <div className="overflow-hidden bg-accent text-white" aria-label="Store information"><div className="marquee-track flex w-max items-center py-4 text-sm font-semibold"><div className="flex items-center gap-12 px-6"><span className="flex items-center gap-2"><MapPin size={17} /> Gatundu–Juja Road, Juja</span><span className="flex items-center gap-2"><Phone size={17} /> +254 721 270 670</span><span>Mon–Fri, 9AM–5PM</span><span aria-hidden="true">◆</span></div><div className="flex items-center gap-12 px-6" aria-hidden="true"><span className="flex items-center gap-2"><MapPin size={17} /> Gatundu–Juja Road, Juja</span><span className="flex items-center gap-2"><Phone size={17} /> +254 721 270 670</span><span>Mon–Fri, 9AM–5PM</span><span>◆</span></div></div></div>
      <section id="about" className="mx-auto grid max-w-7xl gap-12 px-5 py-24 lg:grid-cols-[.9fr_1.1fr] lg:px-8 lg:py-32"><div><p className="eyebrow">The Muhoro standard</p><h2 className="section-title mt-3">Your local partner for <span className="text-accent">serious builds.</span></h2></div><div><p className="text-lg leading-8 text-muted-foreground">Muhoro Steel Hardware Limited is a localized building materials supplier serving Juja and surrounding Kiambu County. We help contractors, fundis, and homeowners get the quality structural and hardware supplies they need — without the runaround.</p><div className="mt-10 grid grid-cols-2 gap-6 border-t border-border pt-7 sm:grid-cols-4">{[['Local','Juja presence'],['Wide','Product range'],['Fast','Site delivery'],['Fair','Pricing']].map(([a,b]) => <div key={a}><p className="font-display text-3xl font-bold text-steel">{a}</p><p className="mt-1 text-sm text-muted-foreground">{b}</p></div>)}</div></div></section>
      <section id="products" className="bg-muted px-5 py-24 lg:px-8 lg:py-32"><div className="mx-auto max-w-7xl"><div className="max-w-2xl"><p className="eyebrow">What we stock</p><h2 className="section-title mt-3">Materials for every <span className="text-accent">stage of the build.</span></h2></div><div className="mt-12 grid gap-5 lg:grid-cols-3">{products.map(({ title, icon: Icon, image, text, items }) => <article key={title} className="group relative isolate flex flex-col overflow-hidden bg-background p-7 shadow-sm transition hover:-translate-y-1 hover:shadow-xl"><Image src={image} alt="" fill unoptimized className="pointer-events-none absolute inset-0 z-0 object-cover opacity-0 transition-opacity duration-300 group-hover:opacity-100 group-focus-within:opacity-100" /><div className="pointer-events-none absolute inset-0 z-0 bg-accent/75 opacity-0 transition-opacity duration-300 group-hover:opacity-100 group-focus-within:opacity-100" /><div className="relative z-10 flex flex-1 flex-col"><div className="mb-8 flex items-center justify-between"><div className="grid h-12 w-12 place-items-center bg-steel text-white transition-colors group-hover:bg-white group-hover:text-accent group-focus-within:bg-white group-focus-within:text-accent"><Icon size={24} /></div><span className="font-mono text-xs font-bold uppercase tracking-widest text-accent transition-colors group-hover:text-white group-focus-within:text-white">Stocked</span></div><h3 className="font-display text-2xl font-bold uppercase text-steel transition-colors group-hover:text-white group-focus-within:text-white">{title}</h3><p className="mt-4 leading-7 text-muted-foreground transition-colors group-hover:text-white/90 group-focus-within:text-white/90">{text}</p><ul className="mt-6 space-y-3 border-t border-border pt-5 text-sm">{items.map(item => <li key={item} className="flex gap-3 transition-colors group-hover:text-white group-focus-within:text-white"><Check size={17} className="mt-0.5 shrink-0 text-accent group-hover:text-white group-focus-within:text-white" />{item}</li>)}</ul><a href="/products" className="mt-8 inline-flex items-center gap-2 text-sm font-bold text-steel transition-colors group-hover:text-white group-focus-within:text-white">Shop this category <ArrowRight size={16} /></a></div></article>)}</div></div></section>
      <section id="delivery" className="bg-steel px-5 py-24 text-steel-foreground lg:px-8 lg:py-28"><div className="mx-auto max-w-7xl"><div className="max-w-2xl"><p className="eyebrow text-accent">From our yard to your site</p><h2 className="section-title mt-3 text-white">Reliable delivery. <span className="text-accent">Less downtime.</span></h2><p className="mt-5 max-w-xl text-lg leading-8 text-steel-foreground/70">For bulk cement, steel bars, and hollow sections, we coordinate dependable delivery across Juja and Kiambu County.</p></div><div className="mt-14 grid gap-8 md:grid-cols-3">{[['01','Order via WhatsApp or call'],['02','We confirm stock & price'],['03','Delivered to your site']].map(([n,t],i) => <div key={n} className="relative border-t border-white/20 pt-6"><span className="font-mono text-sm font-bold text-accent">{n}</span><h3 className="mt-4 font-display text-2xl font-bold uppercase">{t}</h3>{i < 2 && <ArrowRight className="absolute right-4 top-6 hidden text-white/30 md:block" size={24} />}</div>)}</div></div></section>
      <section id="why-muhoro" className="mx-auto max-w-7xl px-5 py-24 lg:px-8 lg:py-32"><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><p className="eyebrow">Why Muhoro</p><h2 className="section-title mt-3">Good materials.<br /><span className="text-accent">Good business.</span></h2></div><div className="grid gap-0 sm:grid-cols-2">{reasons.map((reason, i) => <div key={reason} className="flex gap-4 border-b border-border py-6 sm:odd:mr-8"><span className="font-mono text-sm font-bold text-accent">0{i + 1}</span><div><h3 className="font-display text-xl font-bold uppercase text-steel">{reason}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">Practical service and dependable supply from a team that knows the local building trade.</p></div></div>)}</div></div></section>
      <section id="contact" className="bg-muted px-5 py-24 lg:px-8 lg:py-28"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-2"><div><p className="eyebrow">Start your next project</p><h2 className="section-title mt-3">Let&apos;s get your <span className="text-accent">materials moving.</span></h2><div className="mt-10 space-y-5"><a href="tel:+254721270670" className="flex items-start gap-4"><Phone className="mt-1 text-accent" size={20} /><span><strong className="block text-steel">+254 721 270 670</strong><span className="text-sm text-muted-foreground">Call or WhatsApp for a quick quote</span></span></a><div className="flex items-start gap-4"><MapPin className="mt-1 text-accent" size={20} /><span><strong className="block text-steel">Gatundu–Juja Road, Juja</strong><span className="text-sm text-muted-foreground">Kiambu County, Kenya</span></span></div><p className="pl-9 text-sm text-muted-foreground">Open Monday to Friday, 9AM–5PM</p></div><a href={whatsapp} className="mt-10 inline-flex items-center gap-2 rounded-full bg-whatsapp px-7 py-4 font-bold text-white shadow-lg shadow-whatsapp/20 transition hover:brightness-110">Message Us Now <ArrowRight size={18} /></a></div><div className="relative aspect-[3/2] min-h-[320px] overflow-hidden bg-steel"><Image src="/Muhoro new Isuzu.jpg" alt="Muhoro Steel Hardware's new Isuzu delivery truck" fill unoptimized className="object-cover object-[center_44%]" /><div className="absolute inset-0 bg-[linear-gradient(0deg,rgba(3,46,84,.94)_0%,rgba(3,46,84,.05)_78%)]" /><div className="relative flex h-full min-h-[320px] flex-col justify-end p-8 text-white"><p className="font-mono text-xs font-bold uppercase tracking-widest text-accent">Find us in Juja</p><p className="mt-2 max-w-xs font-display text-3xl font-bold uppercase leading-none">Gatundu–Juja Road</p><a href="https://maps.google.com/?q=Juja%20Kenya" target="_blank" rel="noreferrer" className="mt-5 inline-flex items-center gap-2 text-sm font-bold">Open in Google Maps <ArrowRight size={16} /></a></div></div></div></section>
      <footer className="bg-charcoal px-5 py-12 text-white lg:px-8"><div className="mx-auto flex max-w-7xl flex-col gap-8 sm:flex-row sm:items-end sm:justify-between"><div className="flex items-center gap-3"><img src="/msh-logo.jpg" alt="Muhoro Steel Hardware" className="h-20 w-auto object-contain" /><div><p className="font-display text-xl font-bold">MUHORO <span className="text-accent">STEEL HARDWARE</span></p><p className="mt-1 text-xs text-white/50">Quality steel. Reliable hardware.</p></div></div><div className="flex items-center gap-5"><a href="#products" className="text-sm text-white/60 hover:text-white">Products</a><a href="#contact" className="text-sm text-white/60 hover:text-white">Contact</a><a href="https://www.facebook.com" target="_blank" rel="noreferrer" aria-label="Facebook" className="text-white/60 hover:text-white"><Globe2 size={20} /></a></div></div><div className="mx-auto mt-8 max-w-7xl border-t border-white/10 pt-6 text-xs text-white/40">© 2026 Muhoro Steel Hardware Limited. All rights reserved.</div></footer>
      <a href={whatsapp} aria-label="Chat with Muhoro Steel Hardware on WhatsApp" className="fixed bottom-5 right-5 z-40 grid h-14 w-14 place-items-center rounded-full bg-whatsapp text-white shadow-2xl shadow-whatsapp/30 transition hover:scale-105"><span className="text-xl font-bold">WA</span></a>
    </main>
  )
}
